version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
     - "8876:80"
    depends_on:
      - app
    container_name: tasklist_project_nginx
  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: tasklist_app
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp2/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tasklist
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8110:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8mb3_general_ci
    container_name: tasklist_project_db
  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          - PMA_ARBITRARY=1

